// Generated by gencpp from file package2/TurtleSpeed.msg
// DO NOT EDIT!


#ifndef PACKAGE2_MESSAGE_TURTLESPEED_H
#define PACKAGE2_MESSAGE_TURTLESPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package2
{
template <class ContainerAllocator>
struct TurtleSpeed_
{
  typedef TurtleSpeed_<ContainerAllocator> Type;

  TurtleSpeed_()
    : linear_x(0.0)
    , linear_y(0.0)
    , angular(0.0)  {
    }
  TurtleSpeed_(const ContainerAllocator& _alloc)
    : linear_x(0.0)
    , linear_y(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_x_type;
  _linear_x_type linear_x;

   typedef double _linear_y_type;
  _linear_y_type linear_y;

   typedef double _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::package2::TurtleSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package2::TurtleSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleSpeed_

typedef ::package2::TurtleSpeed_<std::allocator<void> > TurtleSpeed;

typedef boost::shared_ptr< ::package2::TurtleSpeed > TurtleSpeedPtr;
typedef boost::shared_ptr< ::package2::TurtleSpeed const> TurtleSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package2::TurtleSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package2::TurtleSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package2::TurtleSpeed_<ContainerAllocator1> & lhs, const ::package2::TurtleSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.linear_x == rhs.linear_x &&
    lhs.linear_y == rhs.linear_y &&
    lhs.angular == rhs.angular;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package2::TurtleSpeed_<ContainerAllocator1> & lhs, const ::package2::TurtleSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package2::TurtleSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package2::TurtleSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package2::TurtleSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package2::TurtleSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package2::TurtleSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package2::TurtleSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package2::TurtleSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a501a4dc2764ae9fc6458a7afe0f471";
  }

  static const char* value(const ::package2::TurtleSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a501a4dc2764ae9ULL;
  static const uint64_t static_value2 = 0xfc6458a7afe0f471ULL;
};

template<class ContainerAllocator>
struct DataType< ::package2::TurtleSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package2/TurtleSpeed";
  }

  static const char* value(const ::package2::TurtleSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package2::TurtleSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_x  #the x partition of linear speed\n"
"float64 linear_y  #the y partition of linear speed\n"
"float64 angular\n"
;
  }

  static const char* value(const ::package2::TurtleSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package2::TurtleSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_x);
      stream.next(m.linear_y);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package2::TurtleSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package2::TurtleSpeed_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear_x: ";
    Printer<double>::stream(s, indent + "  ", v.linear_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_y: ";
    Printer<double>::stream(s, indent + "  ", v.linear_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular: ";
    Printer<double>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE2_MESSAGE_TURTLESPEED_H
