// Generated by gencpp from file package2/turtle_linear_speed.msg
// DO NOT EDIT!


#ifndef PACKAGE2_MESSAGE_TURTLE_LINEAR_SPEED_H
#define PACKAGE2_MESSAGE_TURTLE_LINEAR_SPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package2
{
template <class ContainerAllocator>
struct turtle_linear_speed_
{
  typedef turtle_linear_speed_<ContainerAllocator> Type;

  turtle_linear_speed_()
    : linear_x(0.0)
    , linear_y(0.0)  {
    }
  turtle_linear_speed_(const ContainerAllocator& _alloc)
    : linear_x(0.0)
    , linear_y(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_x_type;
  _linear_x_type linear_x;

   typedef double _linear_y_type;
  _linear_y_type linear_y;





  typedef boost::shared_ptr< ::package2::turtle_linear_speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package2::turtle_linear_speed_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_linear_speed_

typedef ::package2::turtle_linear_speed_<std::allocator<void> > turtle_linear_speed;

typedef boost::shared_ptr< ::package2::turtle_linear_speed > turtle_linear_speedPtr;
typedef boost::shared_ptr< ::package2::turtle_linear_speed const> turtle_linear_speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package2::turtle_linear_speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package2::turtle_linear_speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package2::turtle_linear_speed_<ContainerAllocator1> & lhs, const ::package2::turtle_linear_speed_<ContainerAllocator2> & rhs)
{
  return lhs.linear_x == rhs.linear_x &&
    lhs.linear_y == rhs.linear_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package2::turtle_linear_speed_<ContainerAllocator1> & lhs, const ::package2::turtle_linear_speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package2::turtle_linear_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package2::turtle_linear_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package2::turtle_linear_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package2::turtle_linear_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package2::turtle_linear_speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package2::turtle_linear_speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package2::turtle_linear_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e20d908e89bc2f6fddbbddd1406770d0";
  }

  static const char* value(const ::package2::turtle_linear_speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe20d908e89bc2f6fULL;
  static const uint64_t static_value2 = 0xddbbddd1406770d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::package2::turtle_linear_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package2/turtle_linear_speed";
  }

  static const char* value(const ::package2::turtle_linear_speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package2::turtle_linear_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_x #the x partition of linear_speed\n"
"float64 linear_y #the y partition of linear_speed\n"
;
  }

  static const char* value(const ::package2::turtle_linear_speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package2::turtle_linear_speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_x);
      stream.next(m.linear_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_linear_speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package2::turtle_linear_speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package2::turtle_linear_speed_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear_x: ";
    Printer<double>::stream(s, indent + "  ", v.linear_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_y: ";
    Printer<double>::stream(s, indent + "  ", v.linear_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE2_MESSAGE_TURTLE_LINEAR_SPEED_H
